use_frameworks!

platform :ios, '10.0'

target 'FunkObjC_Example' do
  pod 'FunkObjC', :path => '../'

  target 'FunkObjC_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'ModernObjC'
  end
end
